version: '3.8'

services:
  timeservice:
    build:
      context: .
      dockerfile: Dockerfile
    image: timeservice:latest
    container_name: timeservice

    # Security: Run as non-root user (already set in Dockerfile)
    # user: "10001:10001"  # Redundant, already USER appuser in Dockerfile

    # Security: Read-only root filesystem
    read_only: true

    # Security: Drop all capabilities
    cap_drop:
      - ALL

    # Security: Prevent privilege escalation
    security_opt:
      - no-new-privileges:true

    # Tmpfs for temporary files (since root filesystem is read-only)
    tmpfs:
      - /tmp:noexec,nosuid,size=10M

    # Port mapping (host:container)
    ports:
      - "8080:8080"

    # Environment variables
    environment:
      - PORT=8080
      # SECURITY: Set explicit CORS origins for production
      # For dev: use ALLOW_CORS_WILDCARD_DEV=true
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8080

    # Restart policy
    restart: unless-stopped

    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M

    # Health check using dedicated probe binary
    healthcheck:
      test: ["CMD", "/app/healthcheck"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
